### ISSUE TITLE
这个链接找不到了

### ISSUE THREAD

**Issue by ankuo** [babyname/fate#110]
![image](https://user-images.githubusercontent.com/54856331/211482607-cf894f5b-d856-43fa-9295-e0fdb09dc084.png)

https://github.com/babyname/fate/releases/download/auto_build/fate_sqlite3_database.zip

访问后 not found

**Comment by godcong** [comment]
谢谢,已修正.
直达链接: https://github.com/babyname/fate/releases/download/v3.5.4/fate_sqlite3_database.zip
