### ISSUE TITLE
怎么自定义喜用神

### ISSUE THREAD

**Issue by GalensGan** [babyname/fate#114]
我发现程序计算的喜用神有点问题，比如：“2023/07/31 09:15” 测算出来的是“土”，根据https://www.zhouyi.cc/bazi/sm/xys/xiyongsheng.php 这个网站计算的，应该是“火”或“木“，
想请问下，在生成名字时，有没有办法指定喜用神呢？
谢谢！

**Comment by GalensGan** [comment]
谢谢回复，我在网上查了下，有的是土，有的是火，https://yisuan.net/app/bazi?_year=2023&_month=7&_day=31&_hour=9 这个网站查询到的是土。
根据你的分析，决定采用土了~

**Comment by GalensGan** [comment]
我查了多个网站，大部分都偏向于 ”火“，大佬，你看是不是算法有没考虑到的地方呢：
https://www.smxs.com/bzxiyongshen/index.html
![image](https://github.com/babyname/fate/assets/45629076/e13812aa-520d-42bb-a211-00cb02ee0eee)

https://xm.99166.com/xys/result.asp
![image](https://github.com/babyname/fate/assets/45629076/4fc49bfc-c372-4fd2-8276-4e35300f2d4a)

**Comment by godcong** [comment]
看你发的"火"的那些是以强五行的算法,
就是哪个强就加哪个...
但自古以来都是强调五行平衡的,在我看来平衡算法更符合实际需求.

**Comment by GalensGan** [comment]
明白了，多谢解惑~
