### ISSUE TITLE
现在的方式太复杂了，需要用到mysql，建议是否可以考虑使用sqlite，简化使用的难度。

### ISSUE THREAD

**Issue by binyly** [babyname/fate#81]
现在的方式太复杂了，需要用到mysql，建议是否可以考虑使用sqlite，简化使用的难度。

**Comment by Z-fly** [comment]
这个项目其实就是godcong一个人的作品，用sqlite起码要重构很多代码。

**Comment by binyly** [comment]
后期如果需要考虑到docker部署，还是可以考虑的，纯建议，酌情处理

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Z-fly <notifications@github.com>
发送时间: Wednesday, September 9, 2020 11:23:51 AM
收件人: godcong/fate <fate@noreply.github.com>
抄送: binyly <yang.bin@live.cn>; Author <author@noreply.github.com>
主题: Re: [godcong/fate] 现在的方式太复杂了，需要用到mysql，建议是否可以考虑使用sqlite，简化使用的难度。 (#81)


这个项目其实就是godcong一个人的作品，用sqlite起码要重构很多代码。

―

**Comment by godcong** [comment]
> 这个项目其实就是godcong一个人的作品，用sqlite起码要重构很多代码。

是的,主要这方面懂的人也不多.能帮助一起维护的人就更少了.
暂时只能一个人维护这个, 许多功能都有想法,但是个人精力,时间跟不上也没办法.

**Comment by design365** [comment]
我觉得不是mysql问题，重点是出来的名字没有个评分排行 ，没法选，太可怕了，一大堆都是偏僻名字。

**Comment by godcong** [comment]
> 我觉得不是mysql问题，重点是出来的名字没有个评分排行 ，没法选，太可怕了，一大堆都是偏僻名字。

你是不是用错库了?
现在用的是2000常用字,怎么会有偏僻字

**Comment by design365** [comment]
> > 我觉得不是mysql问题，重点是出来的名字没有个评分排行 ，没法选，太可怕了，一大堆都是偏僻名字。
> 
> 你是不是用错库了?
> 现在用的是2000常用字,怎么会有偏僻字

不是弄错了， 是出来的名字没有得分排序，全是字之间自由组合出来的，很多都不是朗朗上口，感觉整个名字比较偏僻。
建议从一些古代诗词或者网上常用名字里面去组合，出来的效果才好选名字。

**Comment by hongmaoxiao** [comment]
> > > 我觉得不是mysql问题，重点是出来的名字没有个评分排行 ，没法选，太可怕了，一大堆都是偏僻名字。
> > 
> > 
> > 你是不是用错库了?
> > 现在用的是2000常用字,怎么会有偏僻字
> 
> 不是弄错了， 是出来的名字没有得分排序，全是字之间自由组合出来的，很多都不是朗朗上口，感觉整个名字比较偏僻。
> 建议从一些古代诗词或者网上常用名字里面去组合，出来的效果才好选名字。

最好是道德经，我的一个想法是道德经全部打散 随机组合
