### ISSUE TITLE
【疑问】这个真的可用吗

### ISSUE THREAD

**Issue by flashytime** [babyname/fate#92]
输入我孩子的生日，出来43万+的名字，这个咋选？😄

**Comment by godcong** [comment]
可以选择常用字字库（配置里面regular选择为true）。
最终输出几千字，也可能没有。
如果没有就说明天时不好，选择余地不多。

**Comment by flashytime** [comment]
配置里面regular默认就是true，出来就是40多万个名字，我尝试换成不同的生日，有出现几万个名字的
我感觉有很多字明显不适合作为名字的应该排除掉，比如：乳|艘|腿|呢|踩|踢|葬|瞎|猫|鸦|虾|慰|庙|腰|疮|肿|脑|废|驼|穷|箭|醋|贱|齿|辆|靠|腹|腥|肠|锄|锈|葱|哗|谁|摸|箱|滚|鞋|躺|饼|魄|着|坟|喷|赔|辈|陕|浆|糊|销|稻|傻|院|劈|漆|陡|皱|请|厨|险|惨|漏|磁|摔|敌|葡|缎|摘|罢|层|肤  之类的
