### ISSUE TITLE
建议：字库中去掉一些寓意不好的字

### ISSUE THREAD

**Issue by GalensGan** [babyname/fate#97]
希望字库中可以去掉一些寓意不好的字，或者有个选项，可以设置是否屏蔽，比如“丑”、“痛”、“死”等等

**Comment by godcong** [comment]
会增加自定义去除的.直接去除的话不大好.
像文丑,死死若丸各种也许有人喜欢呢?

**Comment by zhiqunlin** [comment]
这个太辣鸡了

**Comment by zhiqunlin** [comment]
严重怀疑是国外敌对份子来毒害中国人
